### Check Telnet ns
- name: Test altiris node NS reachable
  wait_for:
    host:  "{{ altiris_nodes.altiris_ns }}"
    port: "{{ item }}"
    state: started
    delay: 0
    timeout: 3
  register: check_net_ns
  ignore_errors: yes
  with_items:
    - 80
    - 8443
    - 50123
    - 50124

### Check Telnet pss
- name: Test altiris node PSS reachable
  wait_for:
    host:  "{{ altiris_nodes.altiris_pss }}"
    port: "{{ item }}"
    state: started
    delay: 0
    timeout: 3
  register: check_net_pss
  ignore_errors: yes
  with_items:
    - 80
    - 8443
    - 50124


- set_fact: 
    ns_failed: "{{ altiris_nodes.altiris_ns }} failed on port  {{ check_net_ns | json_query('results[?failed==`true`].item') | join(' ') }}"
  when: check_net_ns is failed

- set_fact: 
    pss_failed: "{{ altiris_nodes.altiris_pss }} failed on port  {{ check_net_pss | json_query('results[?failed==`true`].item') | join(' ') }}"
  when: check_net_pss is failed


### CONTINUO NEL CASO IL CHECK NET HA SUCCESSO

- name: clean altiris resolution to hosts file 
  lineinfile:
    backup: yes
    path: /etc/hosts
    regexp: '(?i).*altiris.*'
    state: absent
  when: check_net_ns is succeeded and check_net_pss is succeeded
  register: hosts_file_clean


- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      172.26.17.212  wp-altiris-ns1  wp-altiris-ns1.lottomatica.net altiris-corp altiris-corp.lottomatica.net
      172.26.17.213  wp-altiris-pss1 wp-altiris-pss1.lottomatica.net
      172.26.17.214  wp-altiris-pss2 wp-altiris-pss2.lottomatica.net
      10.6.139.4  altiris-bus altiris-bus.lottomatica.net
    marker: "# {mark} ALTIRIS BLOCK"
  when: check_net_ns is succeeded and check_net_pss is succeeded

- name: Copy file with owner and permissions
  copy:
    src: files/aex-bootstrap-linux
    dest: /home/administrator/aex-bootstrap-linux
    owner: root
    group: root
    mode: '0744'
  register: copy_file
  when: check_net_ns is succeeded and check_net_pss is succeeded

- name: Execute the script.
  shell: /home/administrator/aex-bootstrap-linux
  register: script_output
  when: check_net_ns is succeeded and check_net_pss is succeeded


- debug: 
    msg: "{{ ns_failed }}"
  when: ns_failed is defined

- debug: 
    msg: "{{ pss_failed }}"
  when: pss_failed is defined

- debug: 
    msg: "{{ script_output }}"
  when: script_output is defined